POST https://3ff2-2001-9e8-e68a-2800-ccd-a110-de2c-8df7.ngrok.io/message/output/telegram/webhook.php HTTP/1.1
content-type: application/json

{
    "message": {
        "from": {
            "id": 653739291,
            "first_name": "Pascal",
            "last_name": "Hürten"
        },
        "text": "Hallo"
    }
}

###
POST https://3ff2-2001-9e8-e68a-2800-ccd-a110-de2c-8df7.ngrok.io/message/output/telegram/webhook.php HTTP/1.1
content-type: application/json

{
    "callback_query": {
        "message": {
            "chat": {
                "id": 653739291
            }
        },
        "data": "advice"
    }
}